[server]
headless = true

[theme]
primaryColor = "#0EA5E9"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1A202C"
font = "sans-serif"

[global]
developmentMode = false
